import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { applicationService } from './services/applicationService'
import { ArrowLeft, ArrowRight, BriefcaseBusiness, CheckCircle2, ClipboardList, Eye, FileText, Search, UserRound, UsersRound } from 'lucide-react'

const steps = [
  ['Personal', UserRound], ['Family', UsersRound], ['Education', FileText], ['Work', BriefcaseBusiness],
  ['Skills & Mobility', ClipboardList], ['Availability', ClipboardList], ['Screening', FileText], ['Declaration', CheckCircle2]
]

const initialForm = {
  personal: { lastName:'', firstName:'', middleName:'', mobileNumber:'', email:'', currentAddress:'', dateOfBirth:'', age:'', sex:'', civilStatus:'', civilStatusOther:'', religion:'', heightCm:'', weightKg:'', positionAppliedFor:'', preferredWorkLocation:'' },
  family: { fatherName:'', fatherOccupation:'', motherName:'', motherOccupation:'', spouseName:'', spouseOccupation:'' },
  education: { highestAttainment:'', courseDegree:'', schoolUniversity:'', yearGraduated:'' },
  work: { experiences:[{company:'',position:'',inclusiveDates:'',reasonLeaving:''},{company:'',position:'',inclusiveDates:'',reasonLeaving:''}], workedInFinancialInstitution:'', financialInstitutionDetails:'' },
  skills: { validDriversLicense:'', driveMotorcycle:'', driveFourWheel:'', },
  availability: { employmentStatus:'', noticePeriod:'', earliestStartDate:'', willingRelocation:'', willingBackgroundCheck:'', expectedMonthlySalary:'' },
  screening: { interestReason:'', personalStrength:'', improvementArea:'', hobbies:'', source:'', sourceOther:'' },
  declaration: { informationAccurate:false, consent:false, applicantName:'', dateSubmitted:'' }
}

function Input({label, value, onChange, type='text', required=false, placeholder='', readOnly=false, autoComplete}) {
  return <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{label}{required && <b className="text-red-500"> *</b>}</span><input type={type} aria-required={required} readOnly={readOnly} autoComplete={autoComplete} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-300 bg-white px-3.5 py-3 outline-none transition focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100" /></label>
}
function Select({label,value,onChange,options,required=false}) { return <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{label}{required && <b className="text-red-500"> *</b>}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-300 bg-white px-3.5 py-3 outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100"><option value="">Select...</option>{options.map(o=><option key={o} value={o}>{o}</option>)}</select></label> }
function Textarea({label,value,onChange,required=false,rows=4}) { return <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{label}{required && <b className="text-red-500"> *</b>}</span><textarea aria-required={required} rows={rows} value={value} onChange={e=>onChange(e.target.value)} className="w-full resize-y rounded-xl border border-slate-300 bg-white px-3.5 py-3 outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100" /></label> }
function RadioGroup({label,value,onChange,options,required=false}) { return <fieldset className="form-radio-group"><legend className="mb-2 text-sm font-medium text-slate-700">{label}{required && <b className="text-red-500"> *</b>}</legend><div className="flex flex-wrap gap-3">{options.map(o=><label key={o} className={`cursor-pointer rounded-xl border px-4 py-3 text-sm transition ${value===o?'border-emerald-600 bg-emerald-50 text-emerald-800':'border-slate-200 bg-white hover:border-emerald-300'}`}><input className="mr-2" type="radio" name={label} value={o} checked={value===o} onChange={()=>onChange(o)}/>{o}</label>)}</div></fieldset> }
function Section({title,subtitle,children}) { return <section className="form-section rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-6 border-b border-slate-100 pb-4"><h2 tabIndex={-1} className="form-section-title text-xl font-bold text-slate-900">{title}</h2>{subtitle&&<p className="mt-1 text-sm text-slate-500">{subtitle}</p>}</div>{children}</section> }

function ApplicationForm() {
  const [form,setForm] = useState(initialForm)
  const [step,setStep] = useState(0)
  const [completedSteps,setCompletedSteps] = useState(0)
  const [saving,setSaving] = useState(false)
  const [error,setError] = useState('')
  const previousStep = useRef(step)
  useEffect(()=>{
    if(previousStep.current===step) return
    previousStep.current=step
    setError('')
    const currentStep=document.querySelector('.application-step.is-current')
    const stepNavigation=currentStep?.parentElement
    if(stepNavigation) stepNavigation.scrollTo({left:Math.max(0,currentStep.offsetLeft-stepNavigation.offsetLeft-(stepNavigation.clientWidth-currentStep.clientWidth)/2),behavior:'auto'})
    const heading=document.querySelector('.form-section-title')
    heading?.focus({preventScroll:true})
    heading?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})
  },[step])
  const [submitted,setSubmitted] = useState(null)
  const navigate = useNavigate()
  const update=(section,key,value)=>setForm(f=>({...f,[section]:{...f[section],[key]:value}}))
  const updateExp=(i,key,value)=>setForm(f=>({...f,work:{...f.work,experiences:f.work.experiences.map((x,idx)=>idx===i?{...x,[key]:value}:x)}}))
  const progress=Math.round((completedSteps/steps.length)*100)

  useEffect(()=>{ if(form.personal.dateOfBirth){ const d=new Date(form.personal.dateOfBirth), now=new Date(); let age=now.getFullYear()-d.getFullYear(); const m=now.getMonth()-d.getMonth(); if(m<0||(m===0&&now.getDate()<d.getDate())) age--; update('personal','age',age>=0?age:'') } },[form.personal.dateOfBirth])

  const validate=()=>{
    if(step===0 && (!form.personal.lastName||!form.personal.firstName||!form.personal.mobileNumber||!form.personal.email||!form.personal.dateOfBirth||!form.personal.sex||!form.personal.civilStatus||!form.personal.positionAppliedFor)) return 'Please complete the required personal information.'
    if(step===2 && !form.education.highestAttainment) return 'Please select your highest educational attainment.'
    if(step===5 && (!form.availability.employmentStatus||!form.availability.earliestStartDate||!form.availability.willingRelocation||!form.availability.willingBackgroundCheck||!form.availability.expectedMonthlySalary)) return 'Please complete the required availability fields.'
    if(step===7 && (!form.declaration.informationAccurate||!form.declaration.consent||!form.declaration.applicantName)) return 'Please confirm both declarations and enter your name.'
    return null
  }
  const next=()=>{ const e=validate(); if(e){setError(e);return} setCompletedSteps(count=>Math.max(count,step+1)); setStep(s=>Math.min(7,s+1)) }
  const submit=async()=>{ const e=validate(); if(e){setError(e);return} setSaving(true); try { const data=await applicationService.submit(form); setCompletedSteps(steps.length); setSubmitted(data); } catch(err){setError(err.message || 'Your application could not be submitted. Please try again.')} finally{setSaving(false)} }
  if(submitted) return <div className="mx-auto max-w-3xl px-4 py-16"><div className="rounded-3xl bg-white p-8 text-center shadow-xl border border-slate-200"><CheckCircle2 className="mx-auto h-16 w-16 text-emerald-600"/><h1 className="mt-5 text-3xl font-bold text-slate-900">Application Submitted</h1><p className="mt-2 text-sm font-semibold text-emerald-700">100% complete</p><p className="mx-auto mt-3 max-w-xl text-slate-600">Thank you for applying to Rural Bank of Medina, Inc. Your application has been received for HR review.</p><div className="mt-6 rounded-2xl bg-slate-50 p-4"><div className="text-xs uppercase tracking-wider text-slate-500">Application Reference</div><div className="mt-1 text-2xl font-bold text-emerald-700">{submitted.referenceNumber}</div></div><button onClick={()=>navigate('/')} className="mt-7 rounded-xl bg-emerald-700 px-5 py-3 font-semibold text-white hover:bg-emerald-800">Submit Another Application</button></div></div>
  return <div className="application-page"><header className="career-hero"><div className="career-container"><div className="career-brand-row"><div className="career-brand"><img src="/rbm.png" alt="Rural Bank of Medina logo" className="career-logo"/><div><p className="career-bank-name">Rural Bank of Medina, Inc.</p><p className="career-department">Human Resources Department</p></div></div><span className="career-badge"><BriefcaseBusiness size={18}/> Careers at RBM</span></div><div className="career-intro"><div className="career-copy"><p className="career-eyebrow">Grow with our community</p><h1>Your next chapter<br/>starts here.</h1><p className="career-description">Take the first step toward a career at Rural Bank of Medina. Tell us about yourself<br className="career-desktop-break"/> through the application below.</p></div><aside className="career-guidance"><div className="career-document-icon"><FileText size={29}/></div><h2>Let’s get to know you</h2><p>Complete all eight sections, then review your details before submitting.</p><span><CheckCircle2 size={18}/> One step at a time</span></aside></div></div></header>
    <main className="career-container application-main"><section className="application-progress" aria-label="Application progress"><div className="progress-heading"><div><p className="progress-eyebrow">Your application</p><p className="progress-current"><strong>Step {step+1} of {steps.length}</strong><span>{steps[step][0]}</span></p></div><span className="progress-percent">{progress}% complete</span></div><div className="progress-track" role="progressbar" aria-label="Application completion" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><div style={{width:`${progress}%`}}/></div><nav className="application-steps" aria-label="Application sections">{steps.map(([name,Icon],i)=>{const StepIcon=i<step?CheckCircle2:Icon;return <button type="button" key={name} onClick={()=>i<step&&setStep(i)} disabled={i>step} aria-current={i===step?'step':undefined} className={`application-step ${i===step?'is-current':i<step?'is-complete':''}`}><span className="step-icon"><StepIcon size={22}/></span><span className="step-name">{name}</span><span className="step-number">{String(i+1).padStart(2,'0')}</span></button>})}</nav></section><div className="application-caption"><span>Applicant information &amp; initial screening</span><span><b>*</b> Required fields</span></div>
      {step===0&&<Section title="A. Personal Information" subtitle="Please provide accurate and complete information."><div className="grid gap-4 md:grid-cols-3"><Input autoComplete="family-name" label="Last Name" value={form.personal.lastName} onChange={v=>update('personal','lastName',v)} required/><Input autoComplete="given-name" label="First Name" value={form.personal.firstName} onChange={v=>update('personal','firstName',v)} required/><Input label="Middle Name" value={form.personal.middleName} onChange={v=>update('personal','middleName',v)}/><Input type="tel" autoComplete="tel" label="Mobile Number" value={form.personal.mobileNumber} onChange={v=>update('personal','mobileNumber',v)} required/><Input autoComplete="email" label="Email Address" type="email" value={form.personal.email} onChange={v=>update('personal','email',v)} required/><Input label="Current Address" value={form.personal.currentAddress} onChange={v=>update('personal','currentAddress',v)}/><Input label="Date of Birth" type="date" value={form.personal.dateOfBirth} onChange={v=>update('personal','dateOfBirth',v)} required/><Input readOnly label="Age" value={form.personal.age} onChange={()=>{}}/><Input label="Religion" value={form.personal.religion} onChange={v=>update('personal','religion',v)}/><Input label="Height (cm)" type="number" value={form.personal.heightCm} onChange={v=>update('personal','heightCm',v)}/><Input label="Weight (kg)" type="number" value={form.personal.weightKg} onChange={v=>update('personal','weightKg',v)}/><Input label="Position Applied For" value={form.personal.positionAppliedFor} onChange={v=>update('personal','positionAppliedFor',v)} required/><Input label="Preferred Work Location / Branch" value={form.personal.preferredWorkLocation} onChange={v=>update('personal','preferredWorkLocation',v)}/></div><div className="mt-6 grid gap-6 md:grid-cols-2"><RadioGroup label="Sex" value={form.personal.sex} onChange={v=>update('personal','sex',v)} options={['Male','Female']} required/><RadioGroup label="Civil Status" value={form.personal.civilStatus} onChange={v=>update('personal','civilStatus',v)} options={['Single','Married','Widowed','Separated','Others']} required/></div>{form.personal.civilStatus==='Others'&&<div className="mt-4 max-w-md"><Input label="Other Civil Status" value={form.personal.civilStatusOther} onChange={v=>update('personal','civilStatusOther',v)}/></div>}</Section>}
      {step===1&&<Section title="B. Family Information"><div className="grid gap-6 md:grid-cols-2"><div className="space-y-4 rounded-2xl bg-slate-50 p-4"><h3 className="font-semibold">Father</h3><Input label="Father's Name" value={form.family.fatherName} onChange={v=>update('family','fatherName',v)}/><Input label="Occupation" value={form.family.fatherOccupation} onChange={v=>update('family','fatherOccupation',v)}/></div><div className="space-y-4 rounded-2xl bg-slate-50 p-4"><h3 className="font-semibold">Mother</h3><Input label="Mother's Name" value={form.family.motherName} onChange={v=>update('family','motherName',v)}/><Input label="Occupation" value={form.family.motherOccupation} onChange={v=>update('family','motherOccupation',v)}/></div><div className="space-y-4 rounded-2xl bg-slate-50 p-4 md:col-span-2"><h3 className="font-semibold">Spouse, if applicable</h3><div className="grid gap-4 md:grid-cols-2"><Input label="Spouse's Name" value={form.family.spouseName} onChange={v=>update('family','spouseName',v)}/><Input label="Occupation" value={form.family.spouseOccupation} onChange={v=>update('family','spouseOccupation',v)}/></div></div></div></Section>}
      {step===2&&<Section title="C. Educational Background"><div className="space-y-6"><RadioGroup label="Highest Educational Attainment" value={form.education.highestAttainment} onChange={v=>update('education','highestAttainment',v)} options={['Senior High School Graduate','College Undergraduate','College Graduate','Post-Graduate']} required/><div className="grid gap-4 md:grid-cols-3"><Input label="Course / Degree" value={form.education.courseDegree} onChange={v=>update('education','courseDegree',v)}/><Input label="School / University" value={form.education.schoolUniversity} onChange={v=>update('education','schoolUniversity',v)}/><Input label="Year Graduated" value={form.education.yearGraduated} onChange={v=>update('education','yearGraduated',v)}/></div></div></Section>}
      {step===3&&<Section title="D. Work Experience" subtitle="Please indicate your two most recent work experiences, if applicable."><div className="space-y-6">{form.work.experiences.map((x,i)=><div key={i} className="rounded-2xl bg-slate-50 p-4"><h3 className="mb-4 font-semibold text-slate-800">Work Experience {i+1} {i===0&&'â€” Most Recent'}</h3><div className="grid gap-4 md:grid-cols-2"><Input label="Company / Employer" value={x.company} onChange={v=>updateExp(i,'company',v)}/><Input label="Position" value={x.position} onChange={v=>updateExp(i,'position',v)}/><Input label="Inclusive Dates" value={x.inclusiveDates} onChange={v=>updateExp(i,'inclusiveDates',v)}/><Input label="Reason for Leaving" value={x.reasonLeaving} onChange={v=>updateExp(i,'reasonLeaving',v)}/></div></div>)}<RadioGroup label="Have you previously worked in a bank, financial institution, cooperative, or similar financial service?" value={form.work.workedInFinancialInstitution} onChange={v=>update('work','workedInFinancialInstitution',v)} options={['Yes','No']}/>{form.work.workedInFinancialInstitution==='Yes'&&<Input label="If Yes, please specify" value={form.work.financialInstitutionDetails} onChange={v=>update('work','financialInstitutionDetails',v)}/>}</div></Section>}
      {step===4&&<Section title="E. Skills, Licenses & Mobility"><div className="space-y-6"><RadioGroup label="Do you have a valid Driver's License?" value={form.skills.validDriversLicense} onChange={v=>update('skills','validDriversLicense',v)} options={['Yes','No']}/><RadioGroup label="Can you drive a motorcycle?" value={form.skills.driveMotorcycle} onChange={v=>update('skills','driveMotorcycle',v)} options={['Yes','No']}/><RadioGroup label="Can you drive a four-wheeled vehicle?" value={form.skills.driveFourWheel} onChange={v=>update('skills','driveFourWheel',v)} options={['Yes','No']}/></div></Section>}
      {step===5&&<Section title="F. Employment Availability"><div className="space-y-6"><RadioGroup label="Current Employment Status" value={form.availability.employmentStatus} onChange={v=>update('availability','employmentStatus',v)} options={['Employed','Unemployed','Fresh Graduate','Self-Employed']} required/>{form.availability.employmentStatus==='Employed'&&<Input label="Notice Period" value={form.availability.noticePeriod} onChange={v=>update('availability','noticePeriod',v)}/>}<div className="grid gap-4 md:grid-cols-2"><Input label="Earliest Available Start Date" type="date" value={form.availability.earliestStartDate} onChange={v=>update('availability','earliestStartDate',v)} required/><Input label="Expected Monthly Salary (â‚±)" type="number" value={form.availability.expectedMonthlySalary} onChange={v=>update('availability','expectedMonthlySalary',v)} required/></div><RadioGroup label="Willing to be assigned to another RBM branch/work location when required?" value={form.availability.willingRelocation} onChange={v=>update('availability','willingRelocation',v)} options={['Yes','No','Subject to Discussion']} required/><RadioGroup label="Willing to undergo pre-employment requirements and background checking?" value={form.availability.willingBackgroundCheck} onChange={v=>update('availability','willingBackgroundCheck',v)} options={['Yes','No']} required/></div></Section>}
      {step===6&&<Section title="G. Initial Interview / Screening Questions"><div className="space-y-5"><Textarea label="Why are you interested in working with Rural Bank of Medina, Inc.?" value={form.screening.interestReason} onChange={v=>update('screening','interestReason',v)} rows={5}/><Textarea label="What personal strength or skill can you contribute to the position?" value={form.screening.personalStrength} onChange={v=>update('screening','personalStrength',v)} rows={5}/><Textarea label="What skill or area are you currently working to improve?" value={form.screening.improvementArea} onChange={v=>update('screening','improvementArea',v)} rows={5}/><Textarea label="During your spare time, what are your usual hobbies or activities?" value={form.screening.hobbies} onChange={v=>update('screening','hobbies',v)} rows={4}/><RadioGroup label="How did you learn about this job opportunity?" value={form.screening.source} onChange={v=>update('screening','source',v)} options={['Facebook/Social Media','Job Posting','Referral','Employee Referral','School/University','Walk-in Application','Other']}/>{form.screening.source==='Other'&&<Input label="Other Source" value={form.screening.sourceOther} onChange={v=>update('screening','sourceOther',v)}/>}</div></Section>}
      {step===7&&<Section title="H. Applicant Declaration & Consent"><div className="rounded-2xl bg-slate-50 p-5 text-sm leading-6 text-slate-600">I certify that the information provided in this form is true, complete, and accurate to the best of my knowledge. I understand that Rural Bank of Medina, Inc. may verify the information provided and process my submitted information for legitimate recruitment and employment-related purposes.</div><div className="mt-5 space-y-3"><label className="flex cursor-pointer gap-3 rounded-xl border border-slate-200 bg-white p-4"><input type="checkbox" checked={form.declaration.informationAccurate} onChange={e=>update('declaration','informationAccurate',e.target.checked)} className="mt-1 h-4 w-4 accent-emerald-700"/><span className="text-sm">I confirm that the information provided is true and accurate.</span></label><label className="flex cursor-pointer gap-3 rounded-xl border border-slate-200 bg-white p-4"><input type="checkbox" checked={form.declaration.consent} onChange={e=>update('declaration','consent',e.target.checked)} className="mt-1 h-4 w-4 accent-emerald-700"/><span className="text-sm">I consent to the processing of my personal information for recruitment and employment-related purposes.</span></label></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Input label="Applicant Name" value={form.declaration.applicantName} onChange={v=>update('declaration','applicantName',v)} required/><Input label="Date Submitted" type="date" value={form.declaration.dateSubmitted} onChange={v=>update('declaration','dateSubmitted',v)}/></div></Section>}
      <div className="application-actions"><div className="application-action-content">{error&&<p role="alert" className="application-error">{error}</p>}<div className="application-action-buttons"><button type="button" disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-5 py-3 font-semibold text-slate-700 disabled:cursor-not-allowed disabled:opacity-40"><ArrowLeft size={18}/> Back</button>{step<7?<button onClick={next} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 font-semibold text-white shadow-sm hover:bg-emerald-800">Continue <ArrowRight size={18}/></button>:<button disabled={saving} onClick={submit} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-6 py-3 font-semibold text-white shadow-sm hover:bg-emerald-800 disabled:opacity-60">{saving?'Submitting...':'Submit Application'} <CheckCircle2 size={18}/></button>}</div></div></div>
    </main><footer className="application-footer"><img src="/rbm.png" alt=""/><span>Rural Bank of Medina, Inc.<small>Human Resources Department</small></span></footer></div>
}

function Admin(){ const [apps,setApps]=useState([]),[q,setQ]=useState(''),[status,setStatus]=useState(''); useEffect(()=>{applicationService.list().then(setApps).catch(()=>{})},[]); const filtered=useMemo(()=>apps.filter(a=>(!status||a.status===status)&&JSON.stringify(a).toLowerCase().includes(q.toLowerCase())),[apps,q,status]); return <div className="min-h-screen bg-slate-50"><header className="bg-emerald-950 text-white"><div className="mx-auto max-w-7xl px-4 py-6 flex items-center justify-between"><div><p className="text-xs uppercase tracking-widest text-emerald-300">HR Administration</p><h1 className="text-2xl font-bold">Applicant Applications</h1></div><Link to="/" className="rounded-xl bg-white/10 px-4 py-2 text-sm">Applicant Form</Link></div></header><main className="mx-auto max-w-7xl px-4 py-8"><div className="mb-5 grid gap-3 md:grid-cols-[1fr_220px]"><div className="relative"><Search className="absolute left-3 top-3.5 text-slate-400" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search applicants..." className="w-full rounded-xl border border-slate-300 bg-white py-3 pl-10 pr-4"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-slate-300 bg-white px-3"><option value="">All Statuses</option><option value="Submitted">Submitted</option><option value="Screening">Screening</option><option value="Interview">Interview</option><option value="Rejected">Rejected</option><option value="Hired">Hired</option></select></div><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="p-4">Reference</th><th className="p-4">Applicant</th><th className="p-4">Position</th><th className="p-4">Email</th><th className="p-4">Status</th><th className="p-4">Submitted</th><th className="p-4"></th></tr></thead><tbody>{filtered.map(a=><tr key={a._id} className="border-t border-slate-100"><td className="p-4 font-semibold text-emerald-700">{a.referenceNumber}</td><td className="p-4">{a.personal?.lastName}, {a.personal?.firstName}</td><td className="p-4">{a.personal?.positionAppliedFor}</td><td className="p-4">{a.personal?.email}</td><td className="p-4"><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">{a.status}</span></td><td className="p-4">{a.createdAt ? new Date(a.createdAt).toLocaleDateString() : ''}</td><td className="p-4"><Link to={`/admin/applications/${a._id}`} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2"><Eye size={16}/> View</Link></td></tr>)}</tbody></table>{!filtered.length&&<div className="p-10 text-center text-slate-500">No applications found.</div>}</div></main></div> }
function Detail(){ const {id}=useParams(); const [a,setA]=useState(null); useEffect(()=>{applicationService.get(id).then(setA)},[id]); if(!a)return <div className="p-10 text-center">Loading...</div>; return <main className="min-h-screen bg-slate-50 p-4 sm:p-8"><div className="mx-auto max-w-5xl"><Link to="/admin" className="inline-flex items-center gap-2 text-sm text-emerald-700"><ArrowLeft size={16}/> Back to Applications</Link><div className="mt-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="text-sm text-slate-500">Application Reference</div><h1 className="text-3xl font-bold text-emerald-800">{a.referenceNumber}</h1></div><span className="h-fit rounded-full bg-emerald-50 px-4 py-2 text-sm font-semibold text-emerald-700">{a.status}</span></div><div className="mt-8 grid gap-5 md:grid-cols-2"><Info title="Applicant" value={`${a.personal?.firstName||''} ${a.personal?.middleName||''} ${a.personal?.lastName||''}`}/><Info title="Position" value={a.personal?.positionAppliedFor}/><Info title="Email" value={a.personal?.email}/><Info title="Mobile" value={a.personal?.mobileNumber}/><Info title="Address" value={a.personal?.currentAddress}/><Info title="Preferred Branch" value={a.personal?.preferredWorkLocation}/><Info title="Education" value={a.education?.highestAttainment}/><Info title="Expected Salary" value={a.availability?.expectedMonthlySalary?`â‚±${a.availability.expectedMonthlySalary}`:''}/></div><div className="mt-8 border-t pt-6"><h2 className="font-bold">Screening Answers</h2><div className="mt-4 space-y-4 text-sm leading-6"><Info title="Interest" value={a.screening?.interestReason}/><Info title="Strength" value={a.screening?.personalStrength}/><Info title="Improvement Area" value={a.screening?.improvementArea}/><Info title="Hobbies" value={a.screening?.hobbies}/></div></div></div></div></main> }
function Info({title,value}){return <div><div className="text-xs font-semibold uppercase tracking-wide text-slate-400">{title}</div><div className="mt-1 whitespace-pre-wrap text-slate-800">{value||'â€”'}</div></div>}
export default function App(){return <Routes><Route path="/" element={<ApplicationForm/>}/><Route path="/admin" element={<Admin/>}/><Route path="/admin/applications/:id" element={<Detail/>}/></Routes>}



